#!/usr/bin/env bash

printf "Running clang-format pre-commit hook... ";

CLANG_FORMAT=$(which clang-format)

if [ ! -x "$CLANG_FORMAT" ]; then
  printf "Error.\n";
  printf "The clang-format cannot be found in your PATH. Please ensure clang-format is installed and on the PATH."
  exit 1
fi

if git rev-parse --verify HEAD >/dev/null 2>&1 ;
then
against=HEAD
else
# Initial commit: diff against an empty tree object
against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Get clang-format output and store it for later checking
clangformatoutput=$(git clang-format --diff --staged -q)

# Redirect output to stderr
exec 1>&2

if [ "$clangformatoutput" != "" ];
then
  printf "Error.\n";
  printf "clang-format detected that changes have been made and are not properly formatted!\n"
  printf "Please run \`git clang-format --staged\`, re-stage modified files, and commit.\n"
  exit 1
else
  printf "Success.\n";
fi
