/*=============================================================================

  Library: CppMicroServices


Copyright Kevlin Henney, 2000, 2001, 2002. All rights reserved.
Extracted from Boost 1.46.1 and adapted for CppMicroServices.

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

=========================================================================*/

#ifndef CPPMICROSERVICES_SAFEFUTURE_H
#define CPPMICROSERVICES_SAFEFUTURE_H

#include "cppmicroservices/BundleContext.h"
#include "cppmicroservices/Framework.h"
#include "cppmicroservices/detail/ScopeGuard.h"

#include <future>
#include <vector>

namespace cppmicroservices
{
    using ActualTask = std::packaged_task<void()>;

    class US_Framework_EXPORT SafeFuture
    {
      public:
        SafeFuture(std::shared_future<void> future,
                   std::shared_ptr<std::atomic<bool>> asyncStarted,
                   std::shared_ptr<ActualTask> task);
        SafeFuture() = default;

        // Destructor
        ~SafeFuture() = default;

        // Copy constructor
        SafeFuture(SafeFuture const& other) = default;

        // Copy assignment operator
        SafeFuture& operator=(SafeFuture const& other) = default;

        // Move constructor
        SafeFuture(SafeFuture&& other) noexcept = default;

        // Move assignment operator
        SafeFuture& operator=(SafeFuture&& other) noexcept = default;

        // Method to get the result
        void get() const;
        void wait() const;
        template <class Rep, class Period>
        std::future_status
        wait_for(std::chrono::duration<Rep, Period> const& timeout_duration) const
        {
            return future.wait_for(timeout_duration);
        }

      private:
        std::shared_future<void> future;
        std::shared_ptr<std::atomic<bool>> asyncStarted;
        std::packaged_task<void()> task;
    };
} // namespace cppmicroservices

#endif // CPPMICROSERVICES_SAFEFUTURE_H
