C++ Micro Services: SharedDataPointer< T > Class Template Reference
--- layout: default title: SharedDataPointer< T > Class Template Reference ---
SharedDataPointer< T > Class Template Reference
Utility Classes
Public Types
typedef T Type
typedef T * pointer
Public Member Functions
void Detach ()
T & operator* ()
const T & operator* () const
T * operator-> ()
const T * operator-> () const
operator T * ()
operator const T * () const
T * Data ()
const T * Data () const
const T * ConstData () const
bool operator== (const SharedDataPointer< T > &other) const
bool operator!= (const SharedDataPointer< T > &other) const
SharedDataPointer ()
~SharedDataPointer ()
SharedDataPointer (T *data)
SharedDataPointer (const SharedDataPointer< T > &o)
SharedDataPointer< T > & operator= (const SharedDataPointer< T > &o)
SharedDataPointer & operator= (T *o)
bool operator! () const
void Swap (SharedDataPointer &other)
Protected Member Functions
T * Clone ()
Member Typedef Documentation
template<class T> typedef T* SharedDataPointer< T >::pointer
template<class T> typedef T SharedDataPointer< T >::Type
Constructor & Destructor Documentation
template<class T> SharedDataPointer< T >::SharedDataPointer () inline
template<class T> SharedDataPointer< T >::~SharedDataPointer () inline
template<class T> SharedDataPointer< T >::SharedDataPointer (T * data) explicit
template<class T> SharedDataPointer< T >::SharedDataPointer (const SharedDataPointer< T > & o) inline
Member Function Documentation
template<class T > T * SharedDataPointer< T >::Clone () protected
template<class T> const T* SharedDataPointer< T >::ConstData () const inline
template<class T> T* SharedDataPointer< T >::Data () inline
template<class T> const T* SharedDataPointer< T >::Data () const inline
template<class T> void SharedDataPointer< T >::Detach () inline
Referenced by SharedDataPointer< ModuleEventData >::Data(), SharedDataPointer< T >::operator T *(), SharedDataPointer< ModuleEventData >::operator*(), and SharedDataPointer< ModuleEventData >::operator->().
template<class T> SharedDataPointer< T >::operator const T * () const inline
template<class T> SharedDataPointer< T >::operator T * () inline
References SharedDataPointer< T >::Detach().
template<class T> bool SharedDataPointer< T >::operator! () const inline
template<class T> bool SharedDataPointer< T >::operator!= (const SharedDataPointer< T > & other) const inline
template<class T> T& SharedDataPointer< T >::operator* () inline
template<class T> const T& SharedDataPointer< T >::operator* () const inline
template<class T> T* SharedDataPointer< T >::operator-> () inline
template<class T> const T* SharedDataPointer< T >::operator-> () const inline
template<class T> SharedDataPointer<T>& SharedDataPointer< T >::operator= (const SharedDataPointer< T > & o) inline
template<class T> SharedDataPointer& SharedDataPointer< T >::operator= (T * o) inline
template<class T> bool SharedDataPointer< T >::operator== (const SharedDataPointer< T > & other) const inline
template<class T> void SharedDataPointer< T >::Swap (SharedDataPointer< T > & other) inline