name: BuildAndTestWindows

on:
  push:
    branches: [ development, c\+\+14-compliant, master ]
  pull_request:
    branches: [ development, c\+\+14-compliant ]
  workflow_dispatch:

jobs:
  detect_vs:
    name: Detect Visual Studio [windows-2025]
    runs-on: windows-2025

    steps:
    - name: Detect Visual Studio
      run: |
        & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -format json
        cmake --version
