name: PerformanceWindows

on:
  push:
  #This workflow runs only on development branch
  #If you want to run performance tests on a particular branch
    #Please add your branch name in branches, e.g. branches: [ development, your_branch_name ]
    branches: [ development , fix-benchmark-workflow]
  workflow_dispatch:

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_CONFIGURATION: 0
  WITH_COVERAGE: 0

jobs:

  benchmark:
    name: CppMicroServices Benchmarks [${{matrix.os}},Configuration=${{matrix.buildconfiguration}}]
    runs-on: ${{matrix.os}}
    env:
      BUILD_DIR: Z:\build\config_${{matrix.buildconfiguration}}
      BUILD_CONFIGURATION: ${{matrix.buildconfiguration}}
      BUILD_OS: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        # build configurations:
        # 0 = threading ON / shared lib ON
        # 1 = threading ON / shared lib OFF
        # 2 = threading OFF / shared lib ON
        # 3 = threading OFF/ shared lib OFF
        buildconfiguration: [0]

    steps:
    - name: Initialization
      run: |
        git config --global core.autocrlf true
        subst Z: ${{github.workspace}}

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build And Test
      working-directory: Z:\
      run: ctest -VV -S cmake\usCTestScript_github.cmake

    - name: Run benchmark and store result in json format
      run: |
        ${{ env.BUILD_DIR }}\bin\Release\usFrameworkBenchTests.exe --benchmark_format=json | tee ${{ env.BUILD_DIR }}\bin\Release\benchmark_result1.json
        ${{ env.BUILD_DIR }}\bin\Release\usConfigurationAdminBenchmarkTests.exe --benchmark_format=json | tee ${{ env.BUILD_DIR }}\bin\Release\benchmark_result2.json
        ${{ env.BUILD_DIR }}\bin\Release\usDeclarativeServicesBenchmarkTests.exe --benchmark_format=json | tee ${{ env.BUILD_DIR }}\bin\Release\benchmark_result3.json

    - name: Merge Benchmark JSON Files
      shell: pwsh
      run: |
        jq -s '[.[0] + .[1] + .[2]]' `
          "${env:BUILD_DIR}/bin/Release/benchmark_result1.json" `
          "${env:BUILD_DIR}/bin/Release/benchmark_result2.json" `
          "${env:BUILD_DIR}/bin/Release/benchmark_result3.json" `
          > "${env:BUILD_DIR}/bin/Release/merged_benchmark_result.json"

    - name: Upload Performance Results as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Performance Results - ${{ github.event.head_commit.author.name }} - ${{ github.sha }}
        path: ${{ env.BUILD_DIR }}\bin\Release\merged_benchmark_result.json
