name: PerformanceWindows

on:
  push:
    branches: [ development, c\+\+14-compliant, master, issue868 ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_CONFIGURATION: 0
  WITH_COVERAGE: 0

jobs:

  benchmark:
    name: CppMicroServices Benchmarks [${{matrix.os}},Configuration=${{matrix.buildconfiguration}}]
    runs-on: ${{matrix.os}}
    env:
      BUILD_DIR: Z:\build\config_${{matrix.buildconfiguration}}
      BUILD_CONFIGURATION: ${{matrix.buildconfiguration}}
      BUILD_OS: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        # build configurations:
        # 0 = threading ON / shared lib ON
        # 1 = threading ON / shared lib OFF
        # 2 = threading OFF / shared lib ON
        # 3 = threading OFF/ shared lib OFF
        buildconfiguration: [0]

    steps:
    - name: Initialization
      run: |
        git config --global core.autocrlf true
        subst Z: ${{github.workspace}}

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build And Test
      working-directory: Z:\
      run: ctest -VV -S cmake\usCTestScript_github.cmake

    - name: Run benchmark and store result in json format
      run: ${{ env.BUILD_DIR }}\bin\Release\usFrameworkBenchTests.exe
        
        